# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeitnehmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('plz', models.CharField(blank=True, max_length=20)),
                ('ort', models.CharField(blank=True, max_length=200)),
                ('land', models.CharField(blank=True, max_length=200)),
                ('uid', models.CharField(blank=True, max_length=20, verbose_name='UID')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank')),
                ('bank_iban', models.CharField(blank=True, max_length=200, verbose_name='IBAN')),
                ('bank_bic', models.CharField(blank=True, max_length=200, verbose_name='BIC')),
            ],
            options={
                'verbose_name': 'Arbeitnehmer',
                'verbose_name_plural': 'Arbeitnehmer',
            },
        ),
        migrations.CreateModel(
            name='Einstellungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mwst', models.IntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Einstellungen',
                'verbose_name_plural': 'Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('plz', models.CharField(blank=True, max_length=20)),
                ('ort', models.CharField(blank=True, max_length=200)),
                ('land', models.CharField(blank=True, max_length=200)),
                ('uid', models.CharField(blank=True, max_length=20, verbose_name='UID')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmen',
            },
        ),
        migrations.CreateModel(
            name='StundenAufzeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('startzeit', models.TimeField()),
                ('endzeit', models.TimeField()),
                ('protokoll', models.TextField()),
                ('bezahlt', models.BooleanField()),
                ('arbeitnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stunden.Arbeitnehmer')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stunden.Firma')),
            ],
            options={
                'verbose_name': 'Stunden Aufzeichnung',
                'verbose_name_plural': 'Stunden Aufzeichnungen',
            },
        ),
    ]
