# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stunden', '0004_rechungsnummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechungsnummer',
            name='rechungsnummer_datum',
            field=models.DateField(auto_now_add=True),
        ),
    ]
