# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stunden', '0005_auto_20161220_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rechungsnummer',
            new_name='Rechnungsnummer',
        ),
        migrations.AlterModelOptions(
            name='rechnungsnummer',
            options={'verbose_name': 'Rechnungsnummer', 'verbose_name_plural': 'Rechnungsnummern'},
        ),
        migrations.RenameField(
            model_name='rechnungsnummer',
            old_name='rechungsnummer',
            new_name='rechnungsnummer',
        ),
        migrations.RenameField(
            model_name='rechnungsnummer',
            old_name='rechungsnummer_datum',
            new_name='rechnungsnummer_datum',
        ),
    ]
