# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stunden', '0006_auto_20161220_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnungsnummer',
            name='rechnungsnummer_datum',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
